name: SonarCloud

# NOTE: no automatic runs for the moment, because it does not work
#on:
#  push:
#    branches:
#      [ master, development, ci ]
#  pull_request:
#      types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

      # NOTE: we cannot disable shallow cloning with huge binary history
      #with:
      #  # Disabling shallow clone is recommended for improving relevancy of reporting
      #  fetch-depth: 0

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: remc2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}